### PR TITLE
Fetch most recent or missing close data for past ten years cron task

### PR DESCRIPTION
**Pull request by justinoboyle**

### CODE REVIEW

**Review by A-very-Cunning-ham — CHANGES_REQUESTED** [review]
Looks good. But should we be ignoring international results? I think we have three options:
- Set the `exchange` param in your requests to `XNAS` so we only get NASDAQ results. But that limits us to one exchange
- Filter EOD data results using a list of exchanges we choose to support
- Ignore any tickers with a non-US country code. Requires additional API call and you have to deal with tickers of the same name on different exchanges

**Comment by justinoboyle** [comment]
> Looks good. But should we be ignoring international results? I think we have three options:
> 
> * Set the `exchange` param in your requests to `XNAS` so we only get NASDAQ results. But that limits us to one exchange
> * Filter EOD data results using a list of exchanges we choose to support
> * Ignore any tickers with a non-US country code. Requires additional API call and you have to deal with tickers of the same name on different exchanges

1. why ignore NYSE?
2. any reason to ignore non-US stocks? most non-NYSE exchanges don't close, and if they do, they follow similar rules as NYSE. we aren't taking holidays into account but they should safely fail and pick up when the markets are open again.

**Comment by justinoboyle** [comment]
worst case is that we don't get data for a specific stock and then it reruns on the next iteration.

**Comment by A-very-Cunning-ham** [comment]
My concern was with duplicated tickers across exchanges. But I played around with the API a bit and now I see that this isn't an issue since you need to specify the exchange in the ticker name if you want something foreign. E.g. `DIS` and `DIS.XMEX`

**Pull request merged**
